spring:
  application:
    name: V1
  data:
    mongodb:
      uri: mongodb+srv://24210066:Q1KUhdBGk9WrVN8w@cluster0.ymcyp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: chefdb
      auto-index-creation: true
